// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Projecttt

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Dropdown8;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Dropdown6;
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label43;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

