// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Projecttt

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_LabelSD;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

